name = "celldefender"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "celldefender-db"
database_id = "" # wrangler d1 create celldefender-db 실행 후 여기에 ID 입력
